Uncaught java.sql.SQLException exception in thread "main" in a method MySQLAccess.preparedState() with signature (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
Exception in thread "main" java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959) [jar:file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/lib/mysql-connector-java-5.1.37/mysql-connector-java-5.1.37-bin.jar!/com/mysql/jdbc/SQLError.class]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) [jar:file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/lib/mysql-connector-java-5.1.37/mysql-connector-java-5.1.37-bin.jar!/com/mysql/jdbc/SQLError.class]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) [jar:file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/lib/mysql-connector-java-5.1.37/mysql-connector-java-5.1.37-bin.jar!/com/mysql/jdbc/SQLError.class]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) [jar:file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/lib/mysql-connector-java-5.1.37/mysql-connector-java-5.1.37-bin.jar!/com/mysql/jdbc/SQLError.class]
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743) [jar:file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/lib/mysql-connector-java-5.1.37/mysql-connector-java-5.1.37-bin.jar!/com/mysql/jdbc/ResultSetImpl.class]
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6320) [jar:file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/lib/mysql-connector-java-5.1.37/mysql-connector-java-5.1.37-bin.jar!/com/mysql/jdbc/ResultSetImpl.class]
	at MySQLAccess.writeResultSet(MySQLAccess.java:36) [file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/bin/MySQLAccess.class]
	at MySQLAccess.preparedState(MySQLAccess.java:79) [file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/bin/MySQLAccess.class]
	at Main.main(Main.java:7) [file:/home/users/inf/wiaw2/iaw47647361/Documents/Mysql/bin/Main.class]
